In [57]:
import pandas as pd
import numpy as np
import spacy
from spacy import displacy
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from itertools import combinations
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from numpy.linalg import norm
from sklearn.feature_extraction.text import CountVectorizer #For Bag of Words
from sklearn.naive_bayes import MultinomialNB #For NB Classifier

%matplotlib inline

In [2]:
df = pd.read_csv('Tweets.csv')

In [3]:
df = df[['airline_sentiment','text']]

In [4]:
df.head()

airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [58]:
#Set target
y = df.airline_sentiment
X = df.text

In [6]:
nlp = spacy.load("en_core_web_lg")

In [34]:
#Bag of Words
corpus = X
vectorizer = CountVectorizer(analyzer = "word", tokenizer = None, preprocessor = None, stop_words = None, max_features = 5000) 
print( vectorizer.fit_transform(corpus).todense() )
print( vectorizer.vocabulary_ )

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'virginamerica': 4788, 'what': 4868, 'said': 3977, 'plus': 3454, 'you': 4981, 've': 4770, 'added': 313, 'commercials': 1025, 'to': 4554, 'the': 4489, 'experience': 1635, 'didn': 1326, 'today': 4555, 'must': 2982, 'mean': 2806, 'need': 3019, 'take': 4430, 'another': 429, 'trip': 4620, 'it': 2431, 'really': 3677, 'aggressive': 346, 'obnoxious': 3141, 'entertainment': 1536, 'in': 2316, 'your': 4983, 'guests': 2060, 'faces': 1670, 'amp': 409, 'they': 4503, 'have': 2129, 'little': 2653, 'recourse': 3708, 'and': 414, 'big': 664, 'bad': 590, 'thing': 4505, 'about': 275, 'seriously': 4087, 'would': 4948, 'pay': 3349, '30': 101, 'flight': 1794, 'for': 1843, 'seats': 4040, 'that': 4487, 'this': 4511, 'playing': 3440, 'only': 3190, 'flying': 1826, 'va': 4760, 'yes': 4975, 'nearly': 3017, 'every': 1585, 'time': 4541, 'fly': 1819, 'vx': 4805, 'won': 4919, 'go': 1983, 'away': 567,

In [59]:
#Split data into test and train
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [37]:
#KNN Scoring Function
def cosine_similarity(a, b):
    numerator = (a @ b)
    denominator = (norm(a) * norm(b))
    return 1 if denominator == 0 else 1 - (numerator / denominator)

In [61]:
#Convert x_train and x_test to vectors
x_train = [nlp(t).vector for t in x_train]
x_test =  [nlp(t).vector for t in x_test]

In [62]:
knn = KNeighborsClassifier(n_neighbors=3, metric=cosine_similarity).fit(x_train, y_train)

In [63]:
knn.score(x_test, y_test)

0.7199453551912568

In [65]:
#Score for Naive Bayes
g = GaussianNB().fit(x_train, y_train)

In [66]:
g.score(x_test, y_test)

0.7049180327868853

KNN for the Win